### ISSUE TITLE
sbus ppm 16ch ?

### ISSUE THREAD

**Issue by ArielBaravalle** [sebseb7/SbusToPPM#4]
y connect the converter to a Frsky X8r  an only can see in the cppm output 12ch.
is possible this?  need to change any configuration ?
i selected in my taranis the channels 1 - 16.

thanks. 

regards.
Ariel

**Comment by athertop** [comment]
Did you ever manage to get 16 channels from PPM side? Is 12ch the limit on this board?

**Comment by sebseb7** [comment]
you can output 16ch if you like, but you have to upload new firmware

**Comment by athertop** [comment]
Which firmware? Do you mean I need to amend the code in some way and upload this to the board? Can you maybe provide some detail?

**Comment by ArielBaravalle** [comment]
I also need the firmware. Please, can you explain more about this?
Thanks

**Comment by ArielBaravalle** [comment]
In the code I can see this options to change 8 or 12ch.  

// 8 or 12
#define PPMCH 12

**Comment by sebseb7** [comment]
You have to build 16ch support in the firmware by yourself if you need that feature.

**Comment by ArielBaravalle** [comment]
Thanks for you reply.
Can you explain me more?  or upload the firmware compiled?
I have a STM programmer but I don't have the know and applications to compile the firmware.
Regards.

**Comment by sebseb7** [comment]
no I cannot help you building 16h support in the firmware, because I don't have a 16CH radio. Beside: this is not an STM project.
