### ISSUE TITLE
Programming advice

### ISSUE THREAD

**Issue by athertop** [sebseb7/SbusToPPM#5]
Hi Seb,

Sorry to bother you here but can't find any other way to get in touch.

I'm wondering if there is a programming guide anywhere for flashing your code to the Atmel Mega88 chip?

I purchased a version of your board from here: http://www.banggood.com/Converter-from-SBUS-to-PPM-or-Spektrum-Serial-p-1016366.html?rmmds=search

but it seems to be 8ch only - I am looking for configuring for 12ch PPM. I have Windows with AVRDUDE installed and can easily get an Atmel flashing tool. Wondering how I compile and flash. 

Many thanks in advance, Paul

**Comment by athertop** [comment]
I figured how to compile a hex file - after following toolchain install notes for the mac from here: http://maxembedded.com/2015/06/setting-up-avr-gcc-toolchain-on-linux-and-mac-os-x/

Just wondering if any special considerations for programming the chip with avrdude (probably with the avrdudess gui

**Comment by sebseb7** [comment]
To update the firmware you need to connect an AVR programmer to the atmel chip, then you should be able to flash the firmware. Please be aware that those boards are "clones" I do not know what kind of crystal they are using or what kind of firmware they use. I have no problem with those "clones". But I don't feel in charge of doing customer care support for them. ;-)

**Comment by athertop** [comment]
Sebseb7, I'm glad to advise that the clone boards on banggood work just fine with your code. I now have 12 channels over ppm (instead of just 8 as it came delivered). I would like to thank you for such a great project. I just now need to figure how to squeeze in 16 channels. Thanks again
