### ISSUE TITLE
Programming the MCU

### ISSUE THREAD

**Issue by yashmulgaonkar** [sebseb7/SbusToPPM#6]
I noticed that the ISP pins are not broken out . Does this board require pre-flashing the MCU before soldering on to the PCB?

Also, I was just wondering if this project is still active?

Thanks!

**Comment by sebseb7** [comment]
Yes you need to flash a bootloader first. They you can use the SBUS pins. I still use the hardware. But I would suggest using this chip today: https://github.com/sebseb7/lpc8xx

**Comment by yashmulgaonkar** [comment]
Hi Seb, Thanks for a prompt reply!

I am planning to make my own layout for my university research project, so I might just add the "SbusToPPM" schematic on the same PCB and breakout the usual SPI pins out and flash it that way. Would you be OK with this?

Thanks!

**Comment by sebseb7** [comment]
sure. You can also use the code without any restrictions. (BSD 0-Clause)
